name: "Bug report"
description: "Report a reproducible problem"
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug.

        If this is a **security** issue, please do not open a public issue. See `SECURITY.md`.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened, and what did you expect to happen?
      placeholder: "Parsing 'tomorrow at 5pm' returns ... but expected ..."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps to reproduce.
      placeholder: |
        1. cargo run -- "..."
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant output. Consider running with `RUSTLING_DEBUG_RULES=1`.
      render: shell

  - type: input
    id: version
    attributes:
      label: Astorion version/commit
      description: git commit SHA or tag.
      placeholder: "e.g. 1a2b3c4"

  - type: input
    id: rust
    attributes:
      label: Rust toolchain
      placeholder: "e.g. rustc 1.76.0 (stable)"

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Linux
        - macOS
        - Windows
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might help (locale, timezone, input domain, etc.).
